---
- name: clear out work dir
  file: path={{ mesos_work_dir }} state=absent
  when: mesos_init_work_dir

# == Work Dir for replicated log
- name: create work dir
  file: path={{ mesos_work_dir }} state=directory

# == Remove default configs
- name: Remove Default Mesos Configs
  file: state=absent path=/etc/mesos/

- name: Remove Mesos ZK File
  file: state=absent path=/etc/mesos/zk

- name: Remove Default Mesos-Master Config
  file: state=absent path=/etc/mesos-master/

- name: Remove Default Mesos-Slave Config
  file: state=absent path=/etc/mesos-slave/

- name: Stop and Disable Mesos-Slave service
  when: mesos_install_mode == "master"
  service: name=mesos-slave state=stopped enabled=no #otherwise should be master-slave
  ignore_errors: yes


# == Configure and recreate
- name: Mesos default config file
  template: src=conf-mesos.j2 dest=/etc/default/mesos
  notify:
    - Restart mesos-master
    - Restart mesos-slave

- name: Mesos Master config file
  template: src=conf-mesos-master.j2 dest=/etc/default/mesos-master
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-master

- name: Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
  notify:
    - Restart mesos-slave

- name: Check if systemd exists
  stat: path=/usr/lib/systemd/system/
  register: systemd_check
  
- name: Mesos master systemd script
  template: src=mesos-master.service.j2 dest=/usr/lib/systemd/system/mesos-master.service
  when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave") and systemd_check.stat.exists == true
  notify:
    - Restart mesos-master

- name: Make sure mesos-master is running
  when: (mesos_install_mode == "master" or mesos_install_mode == "master-slave")
  service: name=mesos-master state=started enabled=yes

- name: Mesos slave systemd script
  template: src=mesos-slave.service.j2 dest=/usr/lib/systemd/system/mesos-slave.service
  when: (mesos_install_mode == "slave" or mesos_install_mode == "master-slave") and systemd_check.stat.exists == true
  notify:
    - Restart mesos-slave

- name: Make sure mesos is running
  when: (mesos_install_mode == "slave" or mesos_install_mode == "master-slave")
  service: name=mesos-slave state=started enabled=yes
